apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: hmisonne/udagram-user
        ports:
        - containerPort: 8080