apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed
  labels:
    app: udagram-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed
  template:
    metadata:
      labels:
        app: udagram-feed
    spec:
      containers:
      - name: udagram-feed
        image: hmisonne/udagram-feed
        ports:
        - containerPort: 8080