version: "3"
services:
  reverseproxy:
      image: hmisonne/udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-user
        - udagram-feed     
  udagram-user:
    image: hmisonne/udagram-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DATABASE 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  udagram-feed:
    image: hmisonne/udagram-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DATABASE 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  frontend:
    image: hmisonne/udagram-frontend
    ports:
      - "8100:80"