apiVersion: v1
kind: Service
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-user

